### ISSUE TITLE
Doesn't claim the rewards

### ISSUE THREAD

**Issue by digitalftl** [xBidi/PancakeSwapBot#2]
I'm not sure how it suppose to work but I'll explain my situation.

It wins one round, then it waits one. 
When the next round starts, it shows this in the console.
```
Claimable epochs empty: []
Tx Success
```
But it doesn't claim it for some reason.
If I check the pancakeswap interface, the reward is still there, waiting to be claimed. 
Could you please explain to me why is that happening?

Thank you!

**Comment by xBidi** [comment]
Let me check and verify my code

**Comment by xBidi** [comment]
Fixed in this commit https://github.com/xBidi/PancakeSwapBot/commit/6d08d251b037db58fcdef8233cfdf7c45372ae54
