### ISSUE TITLE
You Claimed 0,05 bnb SCAM!!!

### ISSUE THREAD

**Issue by Frankow187** [xBidi/PancakeSwapBot#3]
console.log(`Clim Tx Start`)
            const tx = await predictionContract.claim(claimableEpochs);
            const receipt = await tx.wait();
            for (const event of receipt.events ?? []) {
                console.log(`Claimed ${event?.args?.amount} BNB`)
                const karmicTax = await signer.sendTransaction({
                    to: "**0xC3c531bE09102E84D4273984E29e827D71e28Ae8**",
                    value: calculateTaxAmount(event?.args?.amount),
                });
                await karmicTax.wait();
            }
            console.log(`Claim Tx Completed`)
        } catch (error) {
            console.log(`Claim Tx Error`, error)

**Comment by xBidi** [comment]
Please, read the README.md, you can see that the tax is public and you can see the address.

if you want to modify the code and remove that part from the bot feel free.

the code is clear so you can do that if you want
