### ISSUE TITLE
Your strategy just bets the on the bigger payout

### ISSUE THREAD

**Issue by bsc-predict** [xBidi/PancakeSwapBot#5]
Your strategy is very simple and you should state it outright. It bets on the higher payout at the time the bet is made. Your backtest is also inaccurate since it uses the final payout as the bet, but this is not known the time the bet is made.

You should make the strategy explicit in the README as it's simple to understand.

``` const bet = roundBullAmount < roundBearAmount ? 'bull' : 'bear'; ```

https://github.com/xBidi/PancakeSwapBot/blob/main/src/bot.ts#L73

**Comment by xBidi** [comment]
Hi

Yes and no, first of all the strategy used is a martingala with multiplier of 1.6, not 2

as in dont know the final payout at the time i place the bet you can configure an error % wich chnge the bet to random. In real testing around 30% of the time the multipliers change in the last 20 secs, so the backtest is more accurate

**Comment by bsc-predict** [comment]
Great! Thanks for clarifying. Can you please add that to the README for others?
